### ISSUE TITLE
Airports code review

### ISSUE THREAD

**Issue by mandyWW** [jefferyforbes/WhiteHat-Boot-Camp#1]
Great job Jeffery, just a few comments below:

- gitignore, I think just `node_modules` should work, no need to have other versions with / or \
- newPlanes() method in Airport is confusing me - not quite sure what that is doing?
- love the idea of isCarryOn() method in Bags - well done! Although you might want to change this later to push the Bag onto the array rather than the weight of the bag. Also, we tend to name methods that return true/false isXXX but in this case there is no return. So the other option is that you could push onto the correct array as part of construction. Ask me if you want more clarification.
- CrewMember - no need for line 7 as you have passed the name to the superclass (Person). Make it clearer for yourself by specifying the fields of the CrewMember in the code ie:
```
class CrewMember extends Person {
    bags;

    constructor(name) {
        super(name)
        this.bags = [];
    };
};
```
- careful with use of JSDoc style comments instead of normal comments - one left in Bag

Hopefully you have managed to run `jsdoc` ok - I found that if you run `jsdoc .`  it runs on the whole directory

**Comment by jefferyforbes** [comment]
I reviewed and made the changes recommended. I didn't do too much beyond what was listed here.
